version: '3.9'

services:
  flowershopapi:
    build: .
    container_name: flowershopapi
    ports:
      - "5239:8080"
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=rosemary_shop;user=root;password=1234;"
      Jwt__Key: "super_secret_key_12345_very_long_key"
      Jwt__Issuer: "FlowerShopApi"
      Jwt__Audience: "FlowerShopApiUsers"
      GoogleAuth__ClientId: "399688547964-m2697raj5o8apecehmr7lbjj6k3o8cua.apps.googleusercontent.com"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: rosemary_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rosemary_shop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: